apiVersion: v1
kind: Service
metadata:
  name: pokemon-database
  namespace: uhmarcel
  labels:
    name: pokemon-database

spec:
  type: NodePort
  selector:
    app: pokemon-database
  ports:
    - name: entry
      port: 80
      targetPort: 80
      nodePort: 30004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-database
  namespace: uhmarcel
  labels:
    name: pokemon-database
spec:
  selector:
    matchLabels:
      app: pokemon-database
  replicas: 2
  template:
    metadata:
      labels:
        app: pokemon-database
    spec:
      containers:
        - name: pokemon-database
          image: uhmarcel/pokemon-database:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
